#!/bin/sh

########################################
# Set up environment for UV-INDEX FCST
########################################
set -xa
# #### 07/30/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4=' $SECONDS + '
date
#
# obtain unique process id (pid) and make temp directories
#
export pid=$$
export DATA=${DATA:-$DATAROOT/juvi.$pid}
mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z

export MP_LABELIO=YES

####################################
# SENDECF  - Flag Events on SMS
# SENDDBN  - Issue DBNet Client Calls
# SENDCOM  - Copy files to /com directory
# GET_IOPROFILE - Run I/O statistics
####################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_GB2=${SENDDBN_GB2:-YES}
export SENDECF=${SENDECF:-YES}
#export GET_IOPROFILE=NO

#export NET=hourly
export NET=uvi
export RUN=uvi
export model=gfs

export HOMEuvi=${HOMEuvi:-$NWROOT/uvi.${uvi_ver}}
export HOMEuv=$HOMEuvi
export EXECuv=$HOMEuv/exec
export FIXuv=$HOMEuv/fix
export PARMutil=$HOMEuv/parm
export PARMuv=$HOMEuv/parm
export USHuv=$HOMEuv/ush

# Run setup to initialize working directory and utility scripts
msg="JOB $job HAS BEGUN"
postmsg "$msg" 

# Run setpdy and initialize PDY variables
setpdy.sh
. ./PDY
export today=$PDY
export tomorrow=$PDYp1

gfsprod=`compath.py ${envir}/com/gfs/${gfs_ver}`
echo gfsprod=$gfsprod
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${uvi_ver})/${RUN}.${PDY}}
export COMIN_GFS=${COMIN_GFS:-${gfsprod}/gfs.${PDY}}

export pcom=${pcom:-$COMOUT/wmo}
export PCOM=$pcom
mkdir -p $COMOUT $PCOM

env

###################################################
# Execute the Script
###################################################
#
${HOMEuv}/scripts/exuvi.sh
#

cat $pgmout
msg="JOB $job HAS COMPLETED NORMALLY."
echo $msg
postmsg "$msg"

date
############################################
# Remove the Temporary working directory
############################################
if [ "${KEEPDATA^^}" != "YES" ]; then
  rm -rf $DATA
fi
date
