#!/bin/sh

########################################
# Runs UVI Postprocessing up to 24 hours
########################################

set -xa
# #### 08/25/1999 ###################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + '
date
#
# obtain unique process id (pid) and make temp directories
#
export pid=$$
export DATA=${DATA:-$DATAROOT/${job}.${pid}}
mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z

#
# Set up model and cycle specific variables
#
#export NET=hourly
export NET=uvi
export RUN=uvi

export REGION_INDEX="1 2 3 4 5 6 7 8 9"

###################################
# Set up the gempak
##################################
export HOMEuvi=${HOMEuvi:-$NWROOT/uvi.${uvi_ver}}
export HOMEgempak=$HOMEuvi/gempak
export FIXgempak=$HOMEgempak/fix
export USHgempak=$HOMEgempak/ush
export NTSgempak=$USHgempak/restore
export utilscript=$UTILROOT/ush

# Run setup to initialize working directory and utility scripts
# Run setpdy and initialize PDY variables
setpdy.sh
. ./PDY

export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${uvi_ver})/${RUN}.${PDY}}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${uvi_ver})/${RUN}.${PDY}/gempak}


if [ ! -f $COMOUT ]; then 
  mkdir -p -m 775 $COMOUT
fi

env

msg="Begin job for $job"
postmsg "$msg"

########################################################
# Execute the script.
########################################################
${HOMEuvi}/scripts/exuvi_gempak.sh

########################################################
msg="Completed job for $job"
postmsg "$msg"

############################################
# Remove the Temporary working directory
############################################
if [ $KEEPDATA != 'YES' ]; then
   rm -rf $DATA
fi
date

